apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-deployment
  namespace: test
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      application: webpage
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      name: webpage-pod
      labels:
        application: webpage
    spec:
      containers:
      - name: webpage-container
        image: devopscloudautomation/webapplication:Build_Tag
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webpage-service
  namespace: test
spec:
  type: LoadBalancer
  selector:
    application: webpage
  ports:
  - port: 80
    targetPort: 8080